# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  Mode
#' @description function mode() determines the most frequently occurring value in an integer vector (mode).
#'
#' @param x - integer vector
#' @return Integer, containing the most frequently occurring value in the input vector
#'
#' @examples
#'
#' mode(c (5,8,3,9,3,0,1,5,4,5,9))
#' mode(c (1))
#' mode(1:10)
#'
#' @export
mode <- function(x) {
    .Call('HW6_mode', PACKAGE = 'HW6', x)
}

#' @title  perms
#' @description Function perms() generates all the possible permutations of the set {1,2,...,n} (for some given n)
#'
#' @param n - positive integer
#' @return a matrix with n! rows and n columns
#' @examples
#' perms(3)
#' perms(1)
#' @export
perms <- function(n) {
    .Call('HW6_perms', PACKAGE = 'HW6', n)
}

#' @title  simplify2array
#' @description Function simplify2array()  - simplify the list of numeric vectors to numeric matrix
#'
#' @param x - list of numeric vectors
#' @return numeric matrix
#' @examples
#' simplify2array(list(1:2, 3:4, 5:6))
#'
#' x <- list(runif(1000),runif(1000),runif(1000),runif(1000),runif(1000))
#' simplify2array (x)
#'
#' @export
simplify2array <- function(x) {
    .Call('HW6_simplify2array', PACKAGE = 'HW6', x)
}

